### PR TITLE
fix(youtube/remember-playback-speed):  allow to not remember speed

### LINKED ISSUE #1254: The "Remember playback patch "doesn't  work
### Type

Error at runtime

### Bug description

Video playback speed is always remembered no matter what the state of the switch is, so now videos start with the same speed as the last played video

### Steps to reproduce

1-Include "Remember playback speed patch"
2-Select a video and change the playback speed
3-Now this playback speed is also applied to next videos no matter what the state of the switch is (Playback speed is always remembered)

### Relevant log output

```shell
No output
```

### Screenshots or videos

_No response_

### Solution

_No response_

### Additional context

The problem was there since the introduction of the patch , i thought people will report it and it will get fixed quickly but no one did

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### PR DESCRIPTION
**Pull request by LisoUseInAIKyrios**
fix for https://github.com/revanced/revanced-patches/issues/1756

[integration changes](https://github.com/revanced/revanced-integrations/pull/338)

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
> It might be worth renaming the patch to "remember-playback-speed", as the YouTube UI uses 'speed' and not 'rate'.

In that case, refactoring changes will be needed to the class names and other variables, currently, the class name has "rate" but the method has "speed". Internally YouTube uses "rate" which is why I reflected it to the frontend.

File: src/main/kotlin/app/revanced/patches/youtube/misc/video/speed/remember/patch/RememberPlaybackSpeedPatch.kt [hunk 1]
```diff
@@ -18,120 +18,123 @@ import app.revanced.patches.shared.settings.preference.impl.StringResource
...
                 )
             )
         )
 
         context.resolveFingerprints()
 
-        // Set the remembered playback rate.
-        InitializePlaybackRateValuesFingerprint.result!!.apply {
-            // Infer everything necessary for setPlaybackRate()
+        VideoIdPatch.injectCall("${INTEGRATIONS_CLASS_DESCRIPTOR}->newVideoLoaded(Ljava/lang/String;)V")
```
Comment (oSumAtrIX) [inline src/main/kotlin/app/revanced/patches/youtube/misc/video/speed/remember/patch/RememberPlaybackSpeedPatch.kt:61]: Why is this required? The integrations just load the saved playback speed when loading a new video and then the speed is returned at the injection point. Can't the setting simply be returned?

**Review by oSumAtrIX — APPROVED** [review]

File: src/main/kotlin/app/revanced/patches/youtube/misc/video/speed/remember/patch/RememberPlaybackSpeedPatch.kt (hunk 1 above)
Comment (oSumAtrIX) [reply src/main/kotlin/app/revanced/patches/youtube/misc/video/speed/remember/patch/RememberPlaybackSpeedPatch.kt:61]: > then it needs to know when a new video is loaded so it can reset the video speed back to the default.

There is another injection point which is "getCurrentPlaybackSpeed". Why can't you just return the remembered speed there?

**Review by oSumAtrIX — APPROVED** [review]
