### PR TITLE
fix(youtube/litho-filter): use correct type for switch case

### LINKED ISSUE #1066: Some YT Patches Are Failing
### Type

Error while patching

### Bug description

I just downloaded all the new versions of patches, cli and integrations. As i have a Arm-v7 device i tried to patch with cli but some patches failed. I am using recommended yt version (17.43.36)
Rv patches version  2.111.2
Cli version 2.15.1
Integrations version 0.71.0

Cli logs attached below

### Steps to reproduce

Download all required elements for patching with cli.
Start patching and u will see some patches are failing

### Relevant log output

```shell
PS D:\ReVanced> java -jar revanced-cli-all.jar -a youtube.apk -c -d RZ8M323KEHE -o revanced.apk -m integrations.apk -b revanced-patches.jar -e microg-support -e custom-branding -e premium-heading -e enable-debugging -e custom-video-speed -e return-youtube-dislike -e downloads -e theme -e hdr-auto-brightness -e tablet-mini-player -e hide-autoplay-button  --mount
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Merging integrations.apk
WARNING: Skipping unlock-pro, reason: incompatible with com.google.android.youtube. This patch is only compatible with ginlemon.iconpackstudio
WARNING: Skipping tiktok-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping tiktok-speed, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping tiktok-download, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping tiktok-seekbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping tiktok-settings, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping tiktok-force-login, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping tiktok-feed-filter, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping timeline-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
WARNING: Skipping dynamic-color, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
WARNING: Skipping monochrome-icon, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
WARNING: Skipping promo-code-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp
WARNING: Skipping disable-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.myprog.hexedit
WARNING: Skipping spotify-theme, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music
WARNING: Skipping disable-capture-restriction, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music
WARNING: Skipping hide-premium-navbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music
INFO: Skipping hide-autoplay-button, reason: manually excluded
INFO: Skipping return-youtube-dislike, reason: manually excluded
INFO: Skipping theme, reason: manually excluded
INFO: Skipping tablet-mini-player, reason: manually excluded
INFO: Skipping custom-branding, reason: manually excluded
INFO: Skipping premium-heading, reason: manually excluded
INFO: Skipping downloads, reason: manually excluded
INFO: Skipping microg-support, reason: manually excluded
INFO: Skipping custom-video-speed, reason: manually excluded
INFO: Skipping hdr-auto-brightness, reason: manually excluded
WARNING: Skipping unlock-themes, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ticktick.task
INFO: Skipping debug-mode, reason: excluded by default
WARNING: Skipping block-audio-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with tv.twitch.android.app
WARNING: Skipping block-video-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with tv.twitch.android.app
WARNING: Skipping show-deleted-messages, reason: incompatible with com.google.android.youtube. This patch is only compatible with tv.twitch.android.app
WARNING: Skipping pflotsh-ecmwf-subscription-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
WARNING: Skipping tasteBuilder-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping hide-get-premium, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping minimized-playback-music, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping compact-header, reason: excluded by default
WARNING: Skipping upgrade-button-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping music-video-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping music-microg-support, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping premium-icon-reddit, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
WARNING: Skipping general-reddit-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
WARNING: Skipping unlock-pro, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.awedea.nyx
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
INFO: hide-crowdfunding-box succeeded
INFO: hide-time-and-seekbar succeeded
SEVERE: hide-video-buttons failed:
app.revanced.patcher.patch.PatchResultError: 'hide-video-buttons' depends on 'LithoFilterPatch' but the following error was raised: app.revanced.patcher.patch.PatchResultError: Unsupported reference type
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:316)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: enable-wide-searchbar succeeded
INFO: hide-captions-button succeeded
INFO: hide-shorts-button succeeded
INFO: hide-create-button succeeded
INFO: disable-startup-shorts-player succeeded
INFO: hide-endscreen-cards succeeded
INFO: hide-cast-button succeeded
INFO: sponsorblock succeeded
INFO: hide-watch-in-vr succeeded
INFO: hide-album-cards succeeded
INFO: disable-auto-player-popup-panels succeeded
INFO: disable-auto-captions succeeded
INFO: disable-fullscreen-panels succeeded
SEVERE: hide-artist-card failed:
app.revanced.patcher.patch.PatchResultError: 'hide-artist-card' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' did not succeed previously
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:316)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: comments succeeded
INFO: hide-email-address succeeded
INFO: hide-watermark succeeded
INFO: hide-info-cards succeeded
INFO: hide-my-mix succeeded
INFO: old-quality-layout succeeded
SEVERE: general-ads failed:
app.revanced.patcher.patch.PatchResultError: 'general-ads' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' did not succeed previously
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:316)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: video-ads succeeded
INFO: swipe-controls succeeded
INFO: seekbar-tapping succeeded
INFO: settings succeeded
INFO: open-links-directly succeeded
INFO: custom-video-buffer succeeded
INFO: debugging succeeded
INFO: client-spoof succeeded
INFO: always-autorepeat succeeded
INFO: minimized-playback succeeded
INFO: remember-video-quality succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes6.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes8.dex
INFO: Writing dex file classes7.dex
INFO: Writing resources...
INFO: Aligning revanced_raw.apk to revanced_aligned.apk
INFO: Copying revanced_aligned.apk to revanced.apk
INFO: Failed to clean up cache directory
INFO: Installing by mounting
```

### Screenshots or videos

_No response_

### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### PR DESCRIPTION
**Pull request by ghost**
Closes ReVanced/revanced-patches-template#1742.

### CODE REVIEW

File: src/main/kotlin/app/revanced/patches/youtube/misc/litho/filter/patch/LithoFilterPatch.kt [hunk 1]
```diff
@@ -65,22 +65,20 @@ class LithoFilterPatch : BytecodePatch(
...
                         ""
                     ) { it }
-                })${methodReference.returnType}"
+                })${reference.returnType}"
             }
 
-            FieldReference::class -> {
-                val fieldReference = reference as FieldReference
-                "${fieldReference.definingClass}->${fieldReference.name}:${fieldReference.type}"
+            is FieldReference -> {
```
Comment (oSumAtrIX) [inline src/main/kotlin/app/revanced/patches/youtube/misc/litho/filter/patch/LithoFilterPatch.kt:77]: You can ommit the brackets { and }.

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]

File: src/main/kotlin/app/revanced/patches/youtube/misc/litho/filter/patch/LithoFilterPatch.kt (hunk 1 above)
Comment (Canny1913) [reply src/main/kotlin/app/revanced/patches/youtube/misc/litho/filter/patch/LithoFilterPatch.kt]: done

File: src/main/kotlin/app/revanced/patches/youtube/misc/litho/filter/patch/LithoFilterPatch.kt [hunk 2]
```diff
@@ -65,22 +65,17 @@ class LithoFilterPatch : BytecodePatch(
...
+                reference.parameterTypes.joinToString(
+                    ""
+                ) { it }
+            })${reference.returnType}"
 
-            FieldReference::class -> {
-                val fieldReference = reference as FieldReference
-                "${fieldReference.definingClass}->${fieldReference.name}:${fieldReference.type}"
-            }
+
```
Comment (oSumAtrIX) [inline src/main/kotlin/app/revanced/patches/youtube/misc/litho/filter/patch/LithoFilterPatch.kt:75]:
```suggestion
```

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]

**Review by oSumAtrIX — APPROVED** [review]
