### PR TITLE
fix(tiktok): fix patch dependencies issue

### LINKED ISSUE #684: bug: `tiktok-download` patch is failing on all recent TikTok versions and the built app crashes constantly
### Type

Error while patching

### Bug description

Tried multiple versions (`26.2.3`, `26.3.4` and many other) of TikTok both with package names `com.ss.android.ugc.trill` and `com.zhiliaoapp.musically`. This particular patch fails every time and the resulting app crashes both randomly and when try to save a video.

Using the latest versions of manager and patcher.

### Steps to reproduce

1. Download the latest version of TikTok `apk`
2. Try to perform the `tiktok-download` patch

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Deleting existing resource cache directory
Only decoding AndroidManifest.xml because resource patching is disabled
Reading dex files
Applying all patches
Executing 'tiktok-download' of type: bytecode
[error] tiktok-download:app.revanced.patcher.patch.PatchResultError
Repacking patched apk
Creating new dex file
Writing modified dex files
Finished!
```

### Screenshots or videos

_No response_

### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### PR DESCRIPTION
**Pull request by d4rkk3y**
fix ReVanced/revanced-patches-template#2018

### CODE REVIEW

File: src/main/kotlin/app/revanced/patches/tiktok/feedfilter/patch/TiktokFeedFilter.kt [hunk 1]
```diff
@@ -12,14 +12,13 @@ import app.revanced.patcher.patch.annotations.Patch
...
 import app.revanced.patches.tiktok.feedfilter.fingerprints.FeedApiServiceLIZFingerprint
-import app.revanced.patches.tiktok.misc.integrations.patch.TikTokIntegrationsPatch
 import app.revanced.patches.tiktok.misc.settings.fingerprints.SettingsStatusLoadFingerprint
 import app.revanced.patches.tiktok.misc.settings.patch.TikTokSettingsPatch
 import org.jf.dexlib2.Opcode
 import org.jf.dexlib2.iface.instruction.OneRegisterInstruction
 
 @Patch
-@DependsOn([TikTokIntegrationsPatch::class, TikTokSettingsPatch::class])
+@DependsOn([TikTokSettingsPatch::class])
```
Comment (oSumAtrIX) [inline src/main/kotlin/app/revanced/patches/tiktok/feedfilter/patch/TiktokFeedFilter.kt:21]: This patch depends on the integrations, as it references the integrations below in the execute method, why is it removed? Also the patch does not use `TikTokSettingsPatch` anywhere, why is it a dependency?

File: src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt [hunk 2]
```diff
@@ -21,12 +22,14 @@ import app.revanced.patches.tiktok.interaction.downloads.fingerprints.ACLCommonS
...
 import app.revanced.patches.tiktok.interaction.downloads.fingerprints.DownloadPathParentFingerprint
 import app.revanced.patches.tiktok.misc.settings.fingerprints.SettingsStatusLoadFingerprint
+import app.revanced.patches.tiktok.misc.settings.patch.TikTokSettingsPatch
 import org.jf.dexlib2.Opcode
 import org.jf.dexlib2.iface.instruction.OneRegisterInstruction
 import org.jf.dexlib2.iface.instruction.ReferenceInstruction
 import org.jf.dexlib2.iface.reference.StringReference
 
 @Patch
+@DependsOn([TikTokSettingsPatch::class])
```
Comment (oSumAtrIX) [inline src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt:32]: This patch depends on the integrations because it references the integrations below in the smali code, but does not reference `TikTokSettingsPatch` anywhere.

**Review by oSumAtrIX — CHANGES_REQUESTED** [review]

File: src/main/kotlin/app/revanced/patches/tiktok/feedfilter/patch/TiktokFeedFilter.kt (hunk 1 above)
Comment (d4rkk3y) [reply src/main/kotlin/app/revanced/patches/tiktok/feedfilter/patch/TiktokFeedFilter.kt:21]: > Also the patch does not use `TikTokSettingsPatch` anywhere, why is it a dependency?
I thought `DependsOn` be used when a patch need another patch to work. And this patch need settings patch to change the filter option.
> This patch depends on the integrations, as it references the integrations below in the execute method, why is it removed?
It depends on `TikTokSettingsPatch` and `TikTokSettingsPatch` depends on `TikTokIntegrationsPatch`

File: src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt (hunk 2 above)
Comment (d4rkk3y) [reply src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt:32]: This patch is same as above.

File: src/main/kotlin/app/revanced/patches/tiktok/feedfilter/patch/TiktokFeedFilter.kt (hunk 1 above)
Comment (oSumAtrIX) [reply src/main/kotlin/app/revanced/patches/tiktok/feedfilter/patch/TiktokFeedFilter.kt:21]: While `TikTokSettingsPatch` depends on the integrations, this one does too, hence why it should still remain in the array.

File: src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt (hunk 2 above)
Comment (oSumAtrIX) [reply src/main/kotlin/app/revanced/patches/tiktok/interaction/downloads/patch/DownloadsPatch.kt:32]: This patch does depend on `TikTokIntegrationsPatch`, the same way `TikTokSettingsPatch` does. Both should have the patch in the dependency.

**Review by oSumAtrIX — APPROVED** [review]
