### PR TITLE
fix: `hrd-auto-brightness`

### LINKED ISSUE #150: bug(YouTube - Custom video speed): Hold to 2x speed not working while custom speed is selected
### Bug description

When you select custom speed from speed flyout panel, hold to 2x speed doesn't work.  ~~But it works fine when selecting YouTube default speed values.~~

Edit: Even if you select default YouTube speed values still doesn't work. Was working fine yesterday.

### Error logs

```shell
.
```

### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by shadow578**
closes https://github.com/revanced/revanced-patches/issues/150

also see https://github.com/revanced/revanced-integrations/pull/74

### CODE REVIEW

File: src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt [hunk 1]
```diff
@@ -5,7 +5,7 @@ import app.revanced.patcher.annotation.Package
 
 @Compatibility(
     [Package(
-        "com.google.android.youtube", arrayOf("17.24.34", "17.24.35", "17.25.34", "17.26.35")
+        "com.google.android.youtube", arrayOf("17.25.34")
```
Comment (TheJeterLP) [inline src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt:8]: Why did you remove those versions here?

Comment (oSumAtrIX) [reply src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt:8]: Always aim for the latest supported version from the docs.

File: src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt [hunk 2]
```diff
@@ -8,41 +8,49 @@ import app.revanced.patcher.extensions.addInstructions
...
-import app.revanced.patches.youtube.misc.hdrbrightness.fingerprints.HDRBrightnessFingerprint
-import org.jf.dexlib2.iface.instruction.NarrowLiteralInstruction
-import org.jf.dexlib2.iface.instruction.OneRegisterInstruction
+import app.revanced.patches.youtube.misc.hdrbrightness.fingerprints.HDRBrightnessFingerprintXXZ
+import app.revanced.patches.youtube.misc.integrations.patch.IntegrationsPatch
+import org.jf.dexlib2.iface.instruction.ReferenceInstruction
+import org.jf.dexlib2.iface.instruction.TwoRegisterInstruction
+import org.jf.dexlib2.iface.reference.FieldReference
 
 @Patch
```
Comment (TheJeterLP) [inline src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt:21]: That patch should be disabled by default

Comment (oSumAtrIX) [reply src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt:21]: Does this patch conflict with existing features of YouTube?

Comment (oSumAtrIX) [reply src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt:21]: I agree. Also does it not conflict with existing swipe controls?

Comment (TheJeterLP) [reply src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt:21]: > I agree. Also does it not conflict with existing swipe controls?

Since the author of this patch is the same as swipe-controls, I guess not.

File: src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt (hunk 1 above)
Comment (shadow578) [reply src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt:8]: havn't tested those versions, so i cannot tell if the patch is compatible

File: src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt (hunk 2 above)
Comment (shadow578) [reply src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/patch/HDRBrightnessPatch.kt:21]: > I agree. Also does it not conflict with existing swipe controls?

nope, no conflict. only interaction between the two is in integrations

File: src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt (hunk 1 above)
Comment (TheJeterLP) [reply src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt:8]: > havn't tested those versions, so i cannot tell if the patch is compatible

only test the latest one then

Comment (TheJeterLP) [reply src/main/kotlin/app/revanced/patches/youtube/misc/hdrbrightness/annotations/HDRBrightnessCompatibility.kt]: tested and updated 👍🏻
