### PR TITLE
fix(spoof-wifi-connection): use updated instruction indices

### LINKED ISSUE #954: bug: Youtube with spoof-wifi-connection patch crashes immediately
### Type

Error at runtime

### Bug description

Patched youtube with spoof-wifi-connection patch is crashing on start. Without this patch youtube starts fine.
With recommended patches is that same. I have been registering this behavior for several weeks.

### Steps to reproduce

Patch youtube 18.16.37 with revanced-cli commands.

java -jar revanced-cli-2.21.2-dev.2-all.jar \
 -a com.google.android.youtube_18.16.37.apk \
 -m revanced-integrations-0.108.0-dev.17.apk \
 -o YouTube-ReVanced.apk \
 -b revanced-patches-2.174.0-dev.34.jar \
 -i custom-video-buffer \
 -i enable-android-debugging \
 -i export-all-activities \
 -i hide-player-overlay \
 -i predictive-back-gesture \
 -i remove-screenshot-restriction \
 -i remove-player-button-background \
 -i spoof-wifi-connection \
 --experimental

install it as non-root.

### Relevant log output

```shell
05-17 20:20:21.386  9738  9738 E AndroidRuntime: FATAL EXCEPTION: main
05-17 20:20:21.386  9738  9738 E AndroidRuntime: Process: app.revanced.android.youtube, PID: 9738
05-17 20:20:21.386  9738  9738 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class jti: java.lang.Boolean jti.i(alit, long) failed to verify: java.lang.Boolean jti.i(alit, long): [0x93] register v6 has type Long (Low Half) but expected Precise Reference: java.lang.String (declaration of 'jti' appears in base.apk!classes3.dex)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at jst.s(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.n(PG:88)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.a(PG:51)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at ataa.a(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at jxq.o(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.n(PG:89)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.a(PG:51)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at ataa.a(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.j(PG:96)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.a(PG:55)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at ataa.a(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.j(PG:97)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.a(PG:55)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at ataa.a(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at aszz.a(PG:2)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.j(PG:72)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fkk.a(PG:55)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at ataa.a(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at aszz.a(PG:2)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.o(PG:15)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at ija.a(PG:28)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at qq.onCreate(PG:3)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at bt.onCreate(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at fvs.onCreate(PG:8)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at mjq.onCreate(PG:1)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at app.revanced.integrations.swipecontrols.SwipeControlsHostActivity.onCreate(SwipeControlsHostActivity.kt:72)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8108)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8092)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3481)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3683)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:250)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7848)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-17 20:20:21.386  9738  9738 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

### Screenshots or videos

_No response_

### Solution

_No response_

### Additional context

Android 11, moto g9plus, vanced microg instaled, stock youtube is disabled.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

### PR DESCRIPTION
**Pull request by Linus789**
Not using a mutableMethod resulted in using the original method for locating the instruction indices to patch. When another patch already patched that method and the indices got offset, we still used the old indices which resulted in invalid smali.

This is intended to be a temporary fix until a better solution for mutability is found.
Tracking issue: revanced/revanced-patcher#178

reference: revanced/revanced-patches#2177

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
I have changed how methods to be transformed are collected, reducing the number of required checks to a minimum. Please test if everything still works properly.

**Comment by Linus789** [comment]
> I have changed how methods to be transformed are collected, reducing the number of required checks to a minimum. 

If I’m not mistaken, the number of checks are the same. I used a `Sequence` before, which executes lazily. If you agree with me, it would be nice if you would remove your commit.

**Comment by oSumAtrIX** [comment]
The key difference is that the previous code has collected all instructions indices if it matched filterMap, whereas the current one returns, when a single index has been found

**Comment by Linus789** [comment]
Could you point out to me where it collected all instructions indices?

**Comment by oSumAtrIX** [comment]
I believe in line 36 here:

https://github.com/revanced/revanced-patches/blob/bd094580013718541e1874f8e95b46852a33c920/src/main/kotlin/app/revanced/util/patch/AbstractTransformInstructionsPatch.kt#L24-L36

**Comment by Linus789** [comment]
But that doesn’t collect the patch indices, it returns a `Sequence` of patch indices.

**Comment by oSumAtrIX** [comment]
Lazily, I see; in that case, the latest commit doesn't contain any performance regressions and instead skips creating a Sequence

**Comment by Linus789** [comment]
Your perf commit doesn’t contain any performance improvements. It would be nice if you would remove that commit.

**Comment by oSumAtrIX** [comment]
What would be the benefit of removing the commit? It skips having to depend on a Sequence

**Comment by Linus789** [comment]
The code would be more clean and concise since with your commit we have two lines where we `filterMap` an instruction. Before that it was all in one place.

> It skips having to depend on a Sequence

Sounds like premature optimization to me.

**Comment by oSumAtrIX** [comment]
> The code would be more clean and concise since with your commit we have two lines where we filterMap an instruction. 

I believe redundancy comes in favor of readability here to begin with. Previously, it was not able to infer that the code works lazily without knowing Sequence is lazy, thus assuming it collects all indices obfuscating the readability of the code. With the current "redundancy" of `filterMap` existing twice, it is now inferable that first only the method is checked if it's a mutable candidate by checking if an instruction is present that needs to be transformed, without having to first know anything about Sequence or lazy loading.

**Comment by Linus789** [comment]
> Previously, it was not able to infer that the code works lazily without knowing Sequence is lazy, thus assuming it collects all indices obfuscating the readability of the code.

Yes, because you didn’t know of `Sequence`s. Now that you know what a `Sequence` is, the code should be readable. And if you really want to be clear about it being lazy, we could add a comment.

**Comment by oSumAtrIX** [comment]
> > Previously, it was not able to infer that the code works lazily without knowing Sequence is lazy, thus assuming it collects all indices obfuscating the readability of the code.
> 
> Yes, because you didn’t know of `Sequence`s. Now that you know what a `Sequence` is, the code should be readable. And if you really want to be clear about it being lazy, we could add a comment.

I think having to know about something used in a code to justify that the code is readable when it is possible to make it readable solely by reading it obfuscates readability. The code abuses the fact that `Sequence` is lazy to work as expected, but reading the code where `Sequence` is used provides no inference about `Sequence` being lazy, contributing to obfuscating readability. I understand that code quality may outweigh this. If that is your motivation for using a `Sequence,` commenting on how it is leveraged should solve our issue.

**Comment by Linus789** [comment]
> If that is your motivation for using a Sequence, commenting on how it is leveraged should solve our issue.

Thanks for understanding! The other reason why I prefer a sequence over the current code is that I would like to avoid the assumption that the index is never used for filtering (currently always 0 is passed as index).

I will update the code with some comments, but before that I would like to ask another question.

Couldn’t we avoid the copies (referring to my first naive solution) by checking whether a mutable class has already been resolved via the [`resolved`](https://github.com/revanced/revanced-patcher/blob/8f1c83529989bc8e4ae17858fc843a70f89c5fc3/src/main/kotlin/app/revanced/patcher/util/proxy/ClassProxy.kt#L19) field and use the `mutableClass` if it has been resolved and the immutable class if not?

This would have at least two advantages:
* We wouldn’t have to call `filterMap` twice for some instructions
* If another patch adds a new instruction which should have been patched, it would be detected because we are now checking the updated class

And if the `resolved` field needs to be thread-safe, one could use [Lazy#isInitialized](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy/is-initialized.html). The field visibility would have to be changed to public, though.

**Comment by Linus789** [comment]
Well, since this is intended to be a temporary fix, I don’t think it matters that much. I have updated the code with comments regarding the `Sequence`.

File: src/main/kotlin/app/revanced/util/patch/AbstractTransformInstructionsPatch.kt [hunk 1]
```diff
@@ -21,39 +21,44 @@ internal abstract class AbstractTransformInstructionsPatch<T> : BytecodePatch()
...
-                                    }
-                                }.also { if (it.isEmpty()) return@methods }.let { patches ->
-                                    put(method, patches)
-                                }
-                            }
+                val methods = buildList {
+                    classDef.methods.forEach { method ->
+                        // Since the Sequence executes lazily,
+                        // using any() results in only calling
+                        // filterMap until one index has been found.
```
Comment (oSumAtrIX) [inline src/main/kotlin/app/revanced/util/patch/AbstractTransformInstructionsPatch.kt:39]:
```suggestion
                        // filterMap until the first index has been found.
```

**Review by oSumAtrIX — APPROVED** [review]

**Comment by Linus789** [comment]
Thanks for reviewing this PR and helping me with it! :tada:

**Comment by oSumAtrIX** [comment]
Thank you too for your continuous contribution :)
